=== krompa13/YJJLDH_XMLGyak/XMLTASKYJJLDH/XSDYJJLDH.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="jogositvany">
        <xs:complexType>
            <xs:sequence>
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="tanulo" type="tanulotype" />
                    <xs:element name="autosiskola" type="autosiskolatype" />
                    <xs:element name="kreszvizsga" type="kresztype" />
                    <xs:element name="oktato" type="oktatotype" />
                    <xs:element name="jarmu" type="jarmutype" />
                    <xs:element name="forgalmivizsga" type="forgalmitype" />
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- egyedileg definiált komplex típusok -->
    <xs:complexType name="tanulotype">
        <xs:sequence>
            <xs:element name="vezeteknev" type="xs:string"/>
            <xs:element name="keresztnev" type="xs:string"/>
            <xs:element name="szido" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
    </xs:complexType>
    <xs:complexType name="autosiskolatype">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="helyszin" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
    </xs:complexType>
    <xs:complexType name="kresztype">
        <xs:sequence>
            <xs:element name="idopont" type="xs:string"/>
            <xs:element name="eredmeny" type="xs:string"/>
            <xs:element name="vizsgadij" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
        <xs:attribute name="tanuloID" type="xs:unsignedByte" use="required" />
    </xs:complexType>
    <xs:complexType name="oktatotype">
        <xs:sequence>
            <xs:element name="vezeteknev" type="xs:string"/>
            <xs:element name="keresztnev" type="xs:string"/>
            <xs:element name="szido" type="xs:string"/>
        </xs:sequence> 
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
        <xs:attribute name="autosiskolaID" type="xs:unsignedByte" use="required" /> 
    </xs:complexType>
    <xs:complexType name="jarmutype">
        <xs:sequence>
            <xs:element name="gyarto" type="xs:string"/>
            <xs:element name="tipus" type="xs:string"/>
            <xs:element name="evjarat" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="carid" use="required" />
        <xs:attribute name="oktatoID" type="xs:unsignedByte" use="required" />
    </xs:complexType>
    <xs:complexType name="forgalmitype">
        <xs:sequence>
            <xs:element name="idopont" type="xs:string"/>
            <xs:element name="eredmeny" type="xs:string"/>
            <xs:element name="vizsgadij" type="xs:string"/>
            <xs:element name="vizsgaztato" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:unsignedByte" use="required" />
        <xs:attribute name="tanuloID" type="xs:unsignedByte" use="required" />
    </xs:complexType>

    <!-- egyedileg definiált egyszerű típusok -->
    <xs:simpleType name="carid">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}-[0-9]{3}" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== krompa13/YJJLDH_XMLGyak/XMLTASKYJJLDH/DOMParseYJJLDH/XMLyjjldh.updated.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?><jogositvany xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDYJJLDH.xsd">
    <tanulo id="1">
        <vezeteknev>Riz</vezeteknev>
        <keresztnev>Ottó</keresztnev>
        <szido>1999.10.11</szido>
    </tanulo>
    <tanulo id="2">
        <vezeteknev>Bekre</vezeteknev>
        <keresztnev>Pál</keresztnev>
        <szido>1996.07.16</szido>
    </tanulo>
    <tanulo id="3">
        <vezeteknev>Elektrom</vezeteknev>
        <keresztnev>Ágnes</keresztnev>
        <szido>2000.12.03</szido>
    </tanulo>
    <autosiskola id="1">
        <nev>UNI Autósiskola</nev>
        <helyszin>Miskolc</helyszin>
    </autosiskola>
    <autosiskola id="2">
        <nev>Árvai Autósiskola</nev>
        <helyszin>Miskolc</helyszin>
    </autosiskola>
    <kreszvizsga id="1" tanuloID="1">
        <idopont>2021.11.05</idopont>
        <eredmeny>Átment</eredmeny>
        <vizsgadij>4600</vizsgadij>
    </kreszvizsga>
    <kreszvizsga id="2" tanuloID="2">
        <idopont>2021.11.15</idopont>
        <eredmeny>Megbukott</eredmeny>
        <vizsgadij>9200.0</vizsgadij>
    </kreszvizsga>
    <kreszvizsga id="3" tanuloID="3">
        <idopont>2021.11.20</idopont>
        <eredmeny>Átment</eredmeny>
        <vizsgadij>4600</vizsgadij>
    </kreszvizsga>
    <oktato autosiskolaID="1" id="1">
        <vezeteknev>Meg</vezeteknev>
        <keresztnev>Győző</keresztnev>
        <szido>1988.04.16</szido>
    </oktato>
    <oktato autosiskolaID="1" id="2">
        <vezeteknev>Ceruza</vezeteknev>
        <keresztnev>Elemér</keresztnev>
        <szido>1975.10.09</szido>
    </oktato>
    <oktato autosiskolaID="2" id="3">
        <vezeteknev>Fehér</vezeteknev>
        <keresztnev>Farkas</keresztnev>
        <szido>1979.11.16</szido>
    </oktato>
    <oktato autosiskolaID="2" id="4">
        <vezeteknev>Légy</vezeteknev>
        <keresztnev>Ottó</keresztnev>
        <szido>1985.02.16</szido>
    </oktato>
    <jarmu id="SSS-567" oktatoID="1">
        <gyarto>Suzuki</gyarto>
        <tipus>SX4-CROSS</tipus>
        <evjarat>2021</evjarat>
    </jarmu>
    <jarmu id="MLN-391" oktatoID="2">
        <gyarto>Skoda</gyarto>
        <tipus>Octavia</tipus>
        <evjarat>2015</evjarat>
    </jarmu>
    <jarmu id="PPQ-564" oktatoID="3">
        <gyarto>Volkswagen</gyarto>
        <tipus>Golf</tipus>
        <evjarat>2017</evjarat>
    </jarmu>
    <jarmu id="PSW-234" oktatoID="4">
        <gyarto>Opel</gyarto>
        <tipus>Astra</tipus>
        <evjarat>2013</evjarat>
    </jarmu>
    <forgalmivizsga id="1" tanuloID="1">
        <idopont>2021.08.15</idopont>
        <eredmeny>Átment</eredmeny>
        <vizsgadij>11000</vizsgadij>
        <vizsgaztato>Git Áron</vizsgaztato>
    </forgalmivizsga>
    <forgalmivizsga id="2" tanuloID="2">
        <idopont>2021.08.15</idopont>
        <eredmeny>Megbukott</eredmeny>
        <vizsgadij>11000</vizsgadij>
        <vizsgaztato>Git Áron</vizsgaztato>
    </forgalmivizsga>
    <forgalmivizsga id="3" tanuloID="3">
        <idopont>2021.08.20</idopont>
        <eredmeny>Átment</eredmeny>
        <vizsgadij>11000 </vizsgadij>
        <vizsgaztato>Trab Antal</vizsgaztato>
    </forgalmivizsga>
</jogositvany>
